CONFIG_NAME: exocore-eth-devnet
PRESET_BASE: holesky

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# Time parameters
# Do not lower them than (4, 3); otherwise block production is impacted
SECONDS_PER_SLOT: 4
SLOTS_PER_EPOCH: 3

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x6969696969696969696969696969696969696969

# Speed up deposits
# https://github.com/OffchainLabs/eth-pos-devnet/issues/30#issuecomment-2129781827
ETH1_FOLLOW_DISTANCE: 4
EPOCHS_PER_ETH1_VOTING_PERIOD: 2

DEPOSIT_CHAIN_ID: 31337
DEPOSIT_NETWORK_ID: 31337

# Electra params must be supplied, otherwise it complains
ELECTRA_FORK_VERSION: 0x20000094
# Disable Electra, since it's not yet active on any network
ELECTRA_FORK_EPOCH: 0xffffffffffffffff